package v1alpha1

import (
	pager "github.com/munnerz/k8s-api-pager-demo/pkg/apis/pager"
	conversion "k8s.io/apimachinery/pkg/conversion"
	// runtime "k8s.io/apimachinery/pkg/runtime"
	// unsafe "unsafe"
)


// func autoConvert_v1alpha1_TestRunnerSpec_To_pager_TestRunnerSpec(in *TestRunnerSpec, out *pager.TestRunnerSpec, s conversion.Scope) error {
	// out.ObjectMeta = in.ObjectMeta
	// if err := Convert_v1alpha1_AlertSpec_To_pager_AlertSpec(&in.Spec, &out.Spec, s); err != nil {
	// 	return err
	// }
	// if err := Convert_v1alpha1_AlertStatus_To_pager_AlertStatus(&in.Status, &out.Status, s); err != nil {
	// 	return err
	// }
// 	return nil
// }

// Convert_v1alpha1_Alert_To_pager_Alert is an autogenerated conversion function.
func Convert_v1alpha1_TestRunnerSpec_To_pager_TestRunnerSpec(in *TestRunnerSpec, out *pager.TestRunnerSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_TestRunnerSpec_To_pager_TestRunnerSpec(in, out, s)
}
