apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: testruns.srossross.github.io
spec:
  group: srossross.github.io
  version: v1alpha1
  names:
    kind: TestRun
    plural: testruns
  scope: Cluster
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tests.srossross.github.io
spec:
  group: srossross.github.io
  version: v1alpha1
  names:
    kind: Test
    plural: tests
  scope: Cluster
