apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: testruns.srossross.github.io
spec:
  group: srossross.github.io
  version: v1alpha1
  names:
    kind: TestRun
    plural: testruns
  scope: Cluster
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tests.srossross.github.io
spec:
  group: srossross.github.io
  version: v1alpha1
  names:
    kind: Test
    plural: tests
  scope: Cluster
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: test-controller-deployment
  labels:
    app: test-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-controller
  template:
    metadata:
      labels:
        app: test-controller
    spec:
      containers:
      - name: test-controller
        image: srossross/k8s-test-controller:latest
